spring:
  cloud:
    discovery:
      enabled: true
  application:
   name: PAYMENT-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
  